function (generate_shader_binname_from_srcname SHADER_SRC_NAME SHADER_BIN_NAME)
  get_filename_component(EXT ${SHADER_SRC_NAME} LAST_EXT)
  if(EXT)
    string(REGEX MATCH "[A-Za-z0-9]+" TEMP ${EXT})
    string(CONCAT SHADER_BIN_NAME_TEMP ${TEMP} ".spv")
  else(EXT)
    string(CONCAT SHADER_BIN_NAME_TEMP ${SHADER_SRC_NAME} ".spv")
  endif(EXT)
  set(${SHADER_BIN_NAME} ${SHADER_BIN_NAME_TEMP} PARENT_SCOPE)
endfunction()